### ISSUE TITLE
Not compatible with Jackson 2.7+ with lombok @AllArgsConstructor

### ISSUE THREAD

**Issue by zzz1322** [meltmedia/jackson-crypto#6]
I tested this code on Jackson 2.6 and it works pretty fine. However, when I migrated to 2.7 and 2.8, I found out that "deserialize" method in EncryptedJsonDeserializer class is never called, so that we got "Can not deserialize instance of java.lang.String out of START_OBJECT token" exception for a String type that we want to encrypt.

**Comment by ctrimble** [comment]
@zzz1322 That is strange, as I am using this with Jackson 2.8.7 and having success.  If you can reproduce it in a test case, I would be happy to fix it.  Otherwise, I will investigate when I have time.

**Comment by ctrimble** [comment]
If this is an issue, I would expect [this test case to fail](https://github.com/meltmedia/jackson-crypto/blob/develop/src/test/java/com/meltmedia/jackson/crypto/DecryptWithObjectMapperTest.java#L60), after upgrading the Jackson dependency of this project.

**Comment by ctrimble** [comment]
@zzz1322 I have run the existing unit tests against 2.8.7 and everything passes.  I am going to need a failing test case to correct this.

**Comment by zzz1322** [comment]
The issue occurs when using together with lombok @AllArgsConstructor.

For example:

    @NoArgsConstructor
    @AllArgsConstructor
    @Data
    @Builder
    public class POJO {
    
        @Encrypt
        @JsonProperty
        private String value;
    
        public POJO(String value) {
            this.value = value;
        }
    }


Lombok will generate a constructor annotated with @ConstructorProperties({"value"}):

    @java.beans.ConstructorProperties({"value"})
    public POJO(String value) {
        this.value = value;
    }

In this scenario, I found that the deserialization step will fail because Jackson will recognize the type of "value" property as String type. Here is the exception stack trace:


Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: {
  "value" : {
    "envelope" : "ImJsYWgi"
  }
}; line: 2, column: 13] (through reference chain: com.Customer["value"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:261)
	at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1233)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1121)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1074)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:60)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:396)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1194)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2833)
	at com.Main.main(Main.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

We can see that Jackson used "StringDeserializer" for value, leading to an exception.

After some debugging, I found out that the root cause is in BeanDeserializer, deserialize method:

    @Override
    public Object deserialize(JsonParser p, DeserializationContext ctxt) throws IOException
    {
        // common case first
        if (p.isExpectedStartObjectToken()) {
            if (_vanillaProcessing) {
                return vanillaDeserialize(p, ctxt, p.nextToken());
            }
            // 23-Sep-2015, tatu: This is wrong at some many levels, but for now... it is
            //    what it is, including "expected behavior".
            p.nextToken();
            if (_objectIdReader != null) {
                return deserializeWithObjectId(p, ctxt);
            }
            return deserializeFromObject(p, ctxt);
        }
        return _deserializeOther(p, ctxt, p.getCurrentToken());
    }

For Jackson 2.6, _vanillaProcessing is true, but for 2.8, _vanillaProcessing is false.

BeanDeserialize extends BeanDeserializerBase. In BeanDeserializerBase constructor, 

        _vanillaProcessing = !_nonStandardCreation
                && (_injectables == null)
                && !_needViewProcesing
                // also, may need to reorder stuff if we expect Object Id:
                && (_objectIdReader == null)
                ;

_nonStandardCreation differs for 2.6 and 2.8. For 2.6, it is false. For 2.8, it is true.

From several lines above, 

        _nonStandardCreation = (_unwrappedPropertyHandler != null)
            || _valueInstantiator.canCreateUsingDelegate()
            || _valueInstantiator.canCreateFromObjectWith()
            || !_valueInstantiator.canCreateUsingDefault()
            ;

_valueInstantiator.canCreateFromObjectWith() differs. In Jackson 2.6, it returns false, whereas in 2.8 it returns true.

Then, we go to StdValueInstantiator, the type of _valueInstantiator:

    @Override
    public boolean canCreateFromObjectWith() {
        return (_withArgsCreator != null);
    }

Obviously, _withArgsCreator is the root cause for the diverged behavior. 

I understand that we can manually write an all args constructor without the java.beans.ConstructorProperties annotation. But is there an elegant solution for this?

**Comment by ctrimble** [comment]
@zzz1322 thanks for updating this issue with exactly what is going on.  Let me try a couple of things and see if we can get the annotation working with Lombok.  If we just can't get the annotation working, we might be able to expose a way for you to just manually configure which fields use encryption.

**Comment by ctrimble** [comment]
So, I think this has less to do with Lombok and more to do with constructor injection.  I can serialize and then deserialize this bean:

```
public class ConstructorInjected {
  @JsonProperty
  private String value;

  public ConstructorInjected(@JsonProperty("value") String value) {
      this.value = value;
  }
  
  public String getValue() {
    return value;
  }
}
```
but once I add the Encrypted annotation, the test case starts failing with:
```
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: {"value":{"salt":"RaJSkQ==","iv":"4jQS02IdF/cj6WrMpqlVPg==","value":"sFFMommWEPJSaWEIGGAISQ==","cipher":"aes-256-cbc","keyDerivation":"pbkdf2","keyLength":256,"iterations":2000,"keyName":"current"}}; line: 1, column: 2]
```
Correcting this issue should solve the problem being seen here.

**Comment by zzz1322** [comment]
I found a solution for this: Use Jackson 2.9 and disable MapperFeature.INFER_CREATOR_FROM_CONSTRUCTOR_PROPERTIES

**Comment by ctrimble** [comment]
@zzz1322 Great!  Lets keep this open as this should work with or without constructor properties.  I should have time to take another pass at this soon.

**Comment by kandangit** [comment]
Hi,

I have exactly the same problem (jackson 2.8.8, lombok 1.16.10)
For LocalTime , can´t serialize objects coming as string type:
org.springframework.http.converter.HttpMessageNotReadableException: Could not read JSON document: Can not construct instance of java.time.LocalTime: no String-argument constructor/factory method to deserialize from String value ('15:54')

serialization is ok with LocalDate or LocalDateTime

works if remove @AllArgsConstructor


is this a detected bug or there is any workaround?

**Comment by ctrimble** [comment]
@kandangit This project is still incompatible with with Jackson 2.8 and Lombok.  There is a workaround that was posted on May 10th, but it involves upgrading to Jackson 2.9.

**Comment by slavniyteo** [comment]
Workaround posted on May 10th makes jackson disable reading @java.beans.ConstructorProperties.

Another workaround is to make lombok disable adding @java.beans.ConstructorProperties to constructors. Add `lombok.anyConstructor.suppressConstructorProperties = true` to _lombok.config_. 

See [here](https://projectlombok.org/features/configuration) about the lombok configuration file.

**Comment by ctrimble** [comment]
I really wish there was a good way to get this project to work with Lombok out of the box.  Do any of the Lombok users want to add a quick section to the readme, so at least the restrictions are documented?

**Comment by victorwss** [comment]
Maybe https://github.com/rzwitserloot/lombok/issues/1612 is related to this?
